@startuml
hide circle
skinparam linetype ortho
skinparam shadowing false
skinparam packageStyle rectangle
top to bottom direction

package "L1" as L1_RECT #DDDDDD {
    entity "block" as block {
      * id <<PK>>
      --
      hash <<NN>>
      is_canonical <<NN>>
      header <<NN>>
      height <<NN>>
      processed <<NN>>
    }

    entity "l1_msg" as l1_msg {
      * id <<PK>>
      --
      message <<NN>>
      block <<FK>>
      is_transfer <<NN>>
    }

    entity "rollup" as rollup {
      * id <<PK>>
      --
      hash <<NN>>
      start_seq <<NN>>
      end_seq <<NN>>
      time_stamp <<NN>>
      header <<NN>>
      compression_block <<FK>>
    }
}

package "L2" as L2_RECT #DDDDDD {
    entity "batch" as batch {
      * sequence <<PK>>
      --
      converted_hash <<NN>>
      hash <<NN>>
      height <<NN>>
      is_canonical <<NN>>
      header <<NN>>
      l1_proof_hash <<NN>>
      is_executed <<NN>>
    }

    entity "externally_owned_account" as eoa {
      * id <<PK>>
      --
      address <<NN>>
    }

    entity "tx" as tx {
      * id <<PK>>
      --
      hash <<NN>>
      content <<NN>>
      contract <<FK>>
      to_eoa <<FK>>
      type <<NN>>
      sender_address <<FK,NN>>
      idx <<NN>>
      batch_height <<NN>>
      is_synthetic <<NN>>
      time
    }

    entity "receipt" as receipt {
      * id <<PK>>
      --
      post_state
      status <<NN>>
      gas_used <<NN>>
      effective_gas_price
      created_contract_address
      public <<NN>>
      tx <<FK,NN>>
      batch <<FK,NN>>
    }

    entity "receipt_viewer" as receipt_viewer {
      * id <<PK>>
      --
      receipt <<FK,NN>>
      eoa <<FK,NN>>
    }

    entity "contract" as contract {
      * id <<PK>>
      --
      address <<NN>>
      creator <<FK,NN>>
      auto_visibility <<NN>>
      transparent
      tx <<FK,NN>>
    }

    entity "event_type" as event_type {
      * id <<PK>>
      --
      contract <<FK,NN>>
      event_sig <<NN>>
      auto_visibility <<NN>>
      auto_public
      config_public <<NN>>
      topic1_can_view
      topic2_can_view
      topic3_can_view
      sender_can_view
    }

    entity "event_topic" as event_topic {
      * id <<PK>>
      --
      event_type <<FK>>
      topic <<NN>>
      rel_address <<FK>>
    }

    entity "event_log" as event_log {
      * id <<PK>>
      --
      event_type <<FK,NN>>
      topic1 <<FK>>
      topic2 <<FK>>
      topic3 <<FK>>
      datablob
      log_idx <<NN>>
      receipt <<FK,NN>>
    }
}

' =========================
' Relationships (explicit + logical)
' =========================
l1_msg }o--|| block
rollup }o--|| block

receipt }o--|| tx
receipt }o--|| batch

receipt_viewer }o--|| receipt
receipt_viewer }o--|| eoa

contract }o--|| eoa
contract }o--|| tx

event_type }o--|| contract
event_topic }o--|| event_type
event_topic }o--|| eoa

event_log }o--|| event_type
event_log }o--|| event_topic
event_log }o--|| receipt

tx }o--|| contract
tx }o--|| eoa
tx }o--|| eoa

tx }o--|| batch

package "Config" as CFG_RECT #DDDDDD {

    entity "attestation" as attestation {
      * id <<PK>>
      --
      enclave_id <<UQ,NN>>
      pub_key <<NN>>
      report <<NN>>
      node_type <<NN>>
    }

    entity "config" as config {
      * ky <<PK>>
      --
      val <<NN>>
    }
}

package "StateDB (key/value tables)" as STATEDB_RECT #DDDDDD {

  entity "statedb32" as statedb32 {
    * id <<PK>>
    --
    ky <<UQ,NN>>
    val
  }

  entity "statedb33" as statedb33 {
    * id <<PK>>
    --
    ky <<UQ,NN>>
    val
  }

  entity "statedb33_trie_node_account" as statedb33_trie_node_account {
    * id <<PK>>
    --
    ky <<UQ,NN>>
    val
  }

  entity "statedb33_trie_node_storage" as statedb33_trie_node_storage {
    * id <<PK>>
    --
    ky <<UQ,NN>>
    val
  }

  entity "statedb33_state_id" as statedb33_state_id {
    * id <<PK>>
    --
    ky <<UQ,NN>>
    val
  }

  entity "statedb33_code" as statedb33_code {
    * id <<PK>>
    --
    ky <<UQ,NN>>
    val
  }

  entity "statedb33_snapshot_storage" as statedb33_snapshot_storage {
    * id <<PK>>
    --
    ky <<UQ,NN>>
    val
  }

  entity "statedb33_snapshot_account" as statedb33_snapshot_account {
    * id <<PK>>
    --
    ky <<UQ,NN>>
    val
  }

  entity "statedb34" as statedb34 {
    * id <<PK>>
    --
    ky <<UQ,NN>>
    val
  }

  entity "statedb65" as statedb65 {
    * id <<PK>>
    --
    ky <<UQ,NN>>
    val
  }

  entity "triedb_journal" as triedb_journal {
    * id <<PK>>
    --
    val <<NN>>
  }
}
L1_RECT -[hidden]down- L2_RECT
L2_RECT -[hidden]down- CFG_RECT
CFG_RECT -[hidden]down- STATEDB_RECT

@enduml