host:
   debug:
      enableDebugNamespace: true
   log:
     level: 1
     path: ""
enclave:
   debug:
      enableDebugNamespace: true
   log:
     level: 1
     path: ""
network:
   sequencer:
      systemContractsUpgrader: 0xA58C60cc047592DE97BF1E8d2f225Fc5D959De77
