node:
   name: sequencer
   nodeType: sequencer
   isGenesis: true
   id: 0x0654D8B60033144D567f25bF41baC1FB0D60F23B
   privateKey: 8ead642ca80dadb0f346a66cd6aa13e08a8ac7b5c6f7578d4bac96f5db01ac99
   hostAddress: sequencer-host:15000
host:
   p2p:
      bindAddress: 0.0.0.0:15000
   enclave:
      rpcAddresses: [ "sequencer-enclave:11000" ]
enclave:
   db:
      edgelessDBHost: sequencer-edgelessdb
   rpc:
      bindAddress: 0.0.0.0:11000