node:
   name: sequencer
   nodeType: sequencer
   isGenesis: true
   id: 0x9e36779646F7011A3c6D3713b49aEB254258F5d6
   privateKey: e28d878c21a124b5789d244c40a0863613affcc7d918befbb3f94ec0735cdd80
   hostAddress: sequencer-host:15000
host:
   p2p:
      bindAddress: 0.0.0.0:15000
   enclave:
      rpcAddresses: [ "sequencer-enclave:11000" ]
enclave:
   db:
      edgelessDBHost: sequencer-edgelessdb
   rpc:
      bindAddress: 0.0.0.0:11000