CONFIG_NAME: end-to-end
PRESET_BASE: mainnet

# Do not change
DEPOSIT_CHAIN_ID: 1337
DEPOSIT_NETWORK_ID: 1337

# Genesis
GENESIS_FORK_VERSION: 0x000000fd

# Altair
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x010000fd

# Merge
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x020000fd
TERMINAL_TOTAL_DIFFICULTY: 0

# Capella
CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x030000fd
MAX_WITHDRAWALS_PER_PAYLOAD: 16

# Deneb
DENEB_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x040000fd

# Since prysm 6.1.2 doesnt support fulu genesis we have to transition through the forks
# Electra  
ELECTRA_FORK_EPOCH: 1
ELECTRA_FORK_VERSION: 0x050000fd

# Fulu
FULU_FORK_EPOCH: 2
FULU_FORK_VERSION: 0x060000fd

# Time parameters
SECONDS_PER_SLOT: 2
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 1
SHARD_COMMITTEE_PERIOD: 4
ETH1_FOLLOW_DISTANCE: 8

SLOTS_PER_EPOCH: 6
EPOCHS_PER_ETH1_VOTING_PERIOD: 2
MAX_SEED_LOOKAHEAD: 1

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242

BLOB_SCHEDULE:
  # Deneb - start immediately
  - EPOCH: 0
    MAX_BLOBS_PER_BLOCK: 6
  # Electra - increase when Electra activates
  - EPOCH: 1
    MAX_BLOBS_PER_BLOCK: 9
  # Fulu - increase when Fulu activates
  - EPOCH: 2
    MAX_BLOBS_PER_BLOCK: 12