CONFIG_NAME: interop
PRESET_BASE: interop

# Do not change
DEPOSIT_CHAIN_ID: 1337
DEPOSIT_NETWORK_ID: 1337

# Genesis
GENESIS_FORK_VERSION: 0x20000089

# Altair
ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090

# Merge
BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 0

# Capella
CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092
MAX_WITHDRAWALS_PER_PAYLOAD: 16

# DENEB
DENEB_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x20000093

# ELECTRA
ELECTRA_FORK_VERSION: 0x20000094
ELECTRA_FORK_EPOCH: 18446744073709551615

# FULU
FULU_FORK_VERSION: 0x20000095
FULU_FORK_EPOCH: 18446744073709551615

# Time parameters
SECONDS_PER_SLOT: 2
SLOTS_PER_EPOCH: 3

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242