name: '[M] Pause/Unpause All Contracts'
run-name: '[M] ${{ github.event.inputs.action }} All Contracts ( ${{ github.event.inputs.testnet_type }} )'
on:
  workflow_dispatch:
    inputs:
      testnet_type:
        description: 'Testnet Type'
        required: true
        default: 'dev-testnet'
        type: choice
        options:
          - 'dev-testnet'
          - 'uat-testnet'
          - 'sepolia-testnet'
          - 'mainnet'
      action:
        description: 'Action to perform'
        required: true
        default: 'PAUSE'
        type: choice
        options:
          - 'PAUSE'
          - 'UNPAUSE'
      confirmation:
        description: 'Type "confirm" if pausing/unpausing contracts on sepolia or mainnet'
        required: false
        type: string

jobs:
  pause_contracts:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.testnet_type }}

    steps:
      - name: 'Check confirmation'
        run: |
          if [[ ("${{ github.event.inputs.testnet_type }}" == "sepolia-testnet" || "${{ github.event.inputs.testnet_type }}" == "mainnet") && "${{ github.event.inputs.confirmation }}" != "confirm" ]]; then
            echo "Confirmation field must say 'confirm' to ${{ github.event.inputs.action }} contracts on sepolia or mainnet to avoid accidental operations"
            exit 1
          fi

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.25.1

      - name: 'Login to Azure docker registry'
        uses: azure/docker-login@v1
        with:
          login-server: testnetobscuronet.azurecr.io
          username: testnetobscuronet
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'Build and push hardhat deployer image'
        run: |
          DOCKER_BUILDKIT=1 docker build -t ${{ vars.DOCKER_BUILD_TAG_L2_HARDHAT_DEPLOYER }} -f tools/hardhatdeployer/Dockerfile .
          docker push ${{ vars.DOCKER_BUILD_TAG_L2_HARDHAT_DEPLOYER }}

      - name: 'Pause All Contracts'
        id: pauseContracts
        shell: bash
        env:
          DOCKER_API_VERSION: "1.45"
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          # Extract the environment prefix from the input
          TESTNET_TYPE_RAW="${{ github.event.inputs.testnet_type }}"
          if [[ "$TESTNET_TYPE_RAW" == "mainnet" ]]; then
            TESTNET_TYPE="mainnet"
          else
            # Strip the "-testnet" suffix from testnet environments
            TESTNET_TYPE=${TESTNET_TYPE_RAW%-testnet}
          fi
  
          # Run pause all contracts script
          go run ./testnet/launcher/pauseallcontracts/cmd \
          -l1_http_url=${{ secrets.L1_HTTP_URL }} \
          -private_key=${{ secrets.ACCOUNT_PK_WORKER }} \
          -docker_image=${{ vars.DOCKER_BUILD_TAG_L2_HARDHAT_DEPLOYER }} \
          -network_config_addr=${{ vars.NETWORK_CONFIG_ADDR }} \
          -merkle_message_bus_addr=${{ vars.MERKLE_MESSAGE_BUS_ADDR }} \
          -action=${{ github.event.inputs.action }}

      - name: 'Save pause contracts container logs'
        run: |
          docker logs `docker ps -aqf "name=pause-all-contracts"` > pause-all-contracts.out 2>&1

      - name: 'Upload pause contracts container logs'
        uses: actions/upload-artifact@v4
        with:
          name: pause-all-contracts
          path: |
            pause-all-contracts.out
          retention-days: 1
